image: python:2.7

stages:
    - test
    - deploy

appinspect:
  stage: test
  script:
    # first two lines are needed because when gitlab clones the repo it does so with a different set of permissions
    - find src -type d -exec chmod 0755 {} +
    - find src -type f -exec chmod 0644 {} +
    - tar -czvf pyden.tgz -C src pyden
    - tar -czvf pyden-manager.tgz -C src pyden-manager
    - scripts/submit-app.sh pyden
    - pyden_failures=$(echo $?)
    - scripts/submit-app.sh pyden-manager
    - manager_failures=$(echo $?)
    - x=$(( $pyden_failures + $manager_failures ))
    - if [[ $x -gt 0 ]]; then echo "There were $x failures in apps."; exit 1; fi
  artifacts:
    when: always
    paths:
      - pyden.html
      - pyden-manager.html
      - pyden.tgz
      - pyden-manager.tgz
  tags:
    - docker

splunkbase:
  stage: deploy
  script:
    - curl -u ${SPLUNK_CREDS} --request POST https://splunkbase.splunk.com/api/v1/app/4322/new_release/ -F "files[]=@pyden.tgz" -F "filename=pyden.tgz" -F "splunk_versions=7.2" -F "visibility=true"
    - curl -u ${SPLUNK_CREDS} --request POST https://splunkbase.splunk.com/api/v1/app/4323/new_release/ -F "files[]=@pyden-manager.tgz" -F "filename=pyden-manager.tgz" -F "splunk_versions=7.2" -F "visibility=true"
  only:
    - tags