# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

#------------------------------------------------------------------------------
# Configuration you may want to modify
#------------------------------------------------------------------------------
VM_NAME = "splunk"
VM_MEMORY = 2048
VM_CPUS = 2
# this is the password you will set for your splunk admin user
SPLUNK_PASS  = "changeme1"
# Splunk home directory
SPLUNK_HOME  = "/opt/splunk"
SPLUNK_FWD   = "/opt/splunkforwarder"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define "#{VM_NAME}-server" do |splunk|
        splunk.vm.box = "badarsebard/ubuntu-18.04-splunk"
        splunk.vm.box_version = "7.2.4.0"
        splunk.vm.hostname = "#{VM_NAME}-server"
        splunk.vm.network "private_network", ip: "192.168.33.10"
        splunk.vm.provision :hosts do |provisioner|
            provisioner.sync_hosts = true
            provisioner.imports = ['global']
            provisioner.exports = {
                'global' => [
                    ['@vagrant_private_networks', ['@vagrant_hostnames']],
                ],
            }
        end

        splunk.vm.synced_folder "../../src/pyden-manager", "/opt/splunk/etc/apps/pyden-manager", owner: "splunk", group: "splunk"
        splunk.vm.synced_folder "../../src/pyden", "/opt/splunk/etc/deployment-apps/pyden", owner: "splunk", group: "splunk"

        splunk.vm.provider "vmware_desktop" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        splunk.vm.provider "virtualbox" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        splunk.vm.provision "bootstrap", type: "shell" do |s|
            s.privileged = false
            s.name ="Bootstrap Provisioner"
            s.path = "../scripts/provision.sh"
            s.env = {
                :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                :SPLUNK_PASS  => "#{SPLUNK_PASS}"
            }
        end

        splunk.vm.provision "startup", type: "shell", run: "always" do |t|
            t.privileged = false
            t.name ="Start up provisioner"
            t.path = "../scripts/start-splunk.sh"
            t.env = { :SPLUNK_BIN   => "/opt/splunk/bin/splunk" }
        end

        splunk.vm.provision "config serverclass", type: "shell" do |u|
            u.privileged = false
            u.name ="Configuring serverclass"
            u.path = "../scripts/config_serverclass.sh"
            u.env = {
                :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk"
            }
        end

    end

    config.vm.define "#{VM_NAME}-forwarder" do |search|
        search.vm.box = "badarsebard/ubuntu-18.04-splunk_forwarder"
        search.vm.box_version = "7.2.4.0"
        search.vm.hostname = "#{VM_NAME}-forwarder"
        search.vm.network "private_network", ip: "192.168.33.11"
        search.vm.provision :hosts do |provisioner|
            provisioner.sync_hosts = true
            provisioner.imports = ['global']
            provisioner.exports = {
                'global' => [
                    ['@vagrant_private_networks', ['@vagrant_hostnames']],
                ],
            }
        end

        search.vm.provider "vmware_desktop" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        search.vm.provider "virtualbox" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        search.vm.provision "bootstrap", type: "shell" do |s|
            s.privileged = false
            s.name ="Bootstrap Provisioner"
            s.path = "../scripts/provision.sh"
            s.env = {
                :SPLUNK_HOME  => "#{SPLUNK_FWD}",
                :SPLUNK_BIN   => "#{SPLUNK_FWD}/bin/splunk",
                :SPLUNK_PASS   => "#{SPLUNK_PASS}"
            }
        end

        search.vm.provision "startup", type: "shell", run: "always" do |t|
            t.privileged = false
            t.name = "Start up provisioner"
            t.path = "../scripts/start-splunk.sh"
            t.env = {
                :SPLUNK_HOME  => "#{SPLUNK_FWD}",
                :SPLUNK_BIN   => "#{SPLUNK_FWD}/bin/splunk"
            }
        end

        search.vm.provision "config deployment client", type: "shell" do |u|
            u.privileged = false
            u.name = "Configuring deployment client"
            u.path = "../scripts/config_deployment_client.sh"
            u.env = {
                :SPLUNK_HOME  => "#{SPLUNK_FWD}",
                :SPLUNK_BIN   => "#{SPLUNK_FWD}/bin/splunk",
                :SPLUNK_PASS   => "#{SPLUNK_PASS}"
            }
        end
    end
end
