# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

#------------------------------------------------------------------------------
# Configuration you may want to modify
#------------------------------------------------------------------------------
VM_NAME = "splunk"
VM_MEMORY = 2048
VM_CPUS = 2
# this is the password you will set for your splunk admin user
SPLUNK_PASS  = "changeme1"
# Splunk home directory
SPLUNK_HOME  = "/opt/splunk"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define "#{VM_NAME}-indexer" do |indexer|
        indexer.vm.box = "badarsebard/ubuntu-18.04-splunk"
        indexer.vm.box_version = "7.2.3.0"
        indexer.vm.hostname = "#{VM_NAME}-indexer"
        indexer.vm.network "private_network", ip: "192.168.33.10"
        indexer.vm.provision :hosts do |provisioner|
            provisioner.sync_hosts = true
            provisioner.imports = ['global']
            provisioner.exports = {
                'global' => [
                    ['@vagrant_private_networks', ['@vagrant_hostnames']],
                ],
            }
        end

        indexer.vm.provider "vmware_desktop" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        indexer.vm.provider "virtualbox" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        indexer.vm.provision "bootstrap", type: "shell" do |s|
            s.privileged = false
            s.name ="Bootstrap Provisioner"
            s.path = "../scripts/provision.sh"
            s.env = {
                :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                :SPLUNK_PASS  => "#{SPLUNK_PASS}"
            }
        end

        indexer.vm.provision "startup", type: "shell", run: "always" do |t|
            t.privileged = false
            t.name ="Start up provisioner"
            t.path = "../scripts/start-splunk.sh"
            t.env = { :SPLUNK_BIN   => "/opt/splunk/bin/splunk" }
        end
    end

    config.vm.define "#{VM_NAME}-deployer" do |deployer|
        deployer.vm.box = "badarsebard/ubuntu-18.04-splunk"
        deployer.vm.box_version = "7.2.3.0"
        deployer.vm.hostname = "#{VM_NAME}-deployer"
        deployer.vm.network "private_network", ip: "192.168.33.20"
        deployer.vm.provision :hosts do |provisioner|
            provisioner.sync_hosts = true
            provisioner.imports = ['global']
            provisioner.exports = {
                'global' => [
                    ['@vagrant_private_networks', ['@vagrant_hostnames']],
                ],
            }
        end

        deployer.vm.synced_folder "../../src/pyden-manager", "/opt/splunk/etc/apps/pyden-manager", owner: "splunk", group: "splunk"
        deployer.vm.synced_folder "../../src/pyden", "/opt/splunk/etc/shcluster/apps/pyden", owner: "splunk", group: "splunk"
        deployer.vm.synced_folder "../../src/test-app", "/opt/splunk/etc/shcluster/apps/test-app", owner: "splunk", group: "splunk"

        deployer.vm.provider "vmware_desktop" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        deployer.vm.provider "virtualbox" do |v|
            v.memory = "#{VM_MEMORY}"
            v.cpus = "#{VM_CPUS}"
        end

        deployer.vm.provision "bootstrap", type: "shell" do |s|
            s.privileged = false
            s.name ="Bootstrap Provisioner"
            s.path = "../scripts/provision.sh"
            s.env = {
                :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                :SPLUNK_PASS  => "#{SPLUNK_PASS}"
            }
        end

        deployer.vm.provision "startup", type: "shell", run: "always" do |t|
            t.privileged = false
            t.name ="Start up provisioner"
            t.path = "../scripts/start-splunk.sh"
            t.env = { :SPLUNK_BIN   => "/opt/splunk/bin/splunk" }
        end

        deployer.vm.provision "add peer", type: "shell" do |u|
            u.privileged = false
            u.name = "Adding peer node"
            u.path = "../scripts/add_peer.sh"
            u.env = {
                :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                :SPLUNK_PASS  => "#{SPLUNK_PASS}"
            }
        end

        deployer.vm.provision "configure deployer", type: "shell" do |v|
            v.privileged = false
            v.name = "Configuring server as deployer"
            v.path = "../scripts/config_deployer.sh"
            v.env = {
                :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                :SPLUNK_PASS  => "#{SPLUNK_PASS}"
            }
        end
    end

    (1..3).each do |i|
        config.vm.define "#{VM_NAME}-search-#{i}" do |search|
            search.vm.box = "badarsebard/ubuntu-18.04-splunk"
            search.vm.box_version = "7.2.3.0"
            search.vm.hostname = "#{VM_NAME}-search-#{i}"
            search.vm.network "private_network", ip: "192.168.33.2#{i}"
            search.vm.provision :hosts do |provisioner|
                provisioner.sync_hosts = true
                provisioner.imports = ['global']
                provisioner.exports = {
                    'global' => [
                        ['@vagrant_private_networks', ['@vagrant_hostnames']],
                    ],
                }
            end

            search.vm.provider "vmware_desktop" do |v|
                v.memory = "#{VM_MEMORY}"
                v.cpus = "#{VM_CPUS}"
            end

            search.vm.provider "virtualbox" do |v|
                v.memory = "#{VM_MEMORY}"
                v.cpus = "#{VM_CPUS}"
            end

            search.vm.provision "bootstrap", type: "shell" do |s|
                s.privileged = false
                s.name ="Bootstrap Provisioner"
                s.path = "../scripts/provision.sh"
                s.env = {
                    :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                    :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                    :SPLUNK_PASS  => "#{SPLUNK_PASS}"
                }
            end

            search.vm.provision "startup", type: "shell", run: "always" do |t|
                t.privileged = false
                t.name = "Start up provisioner"
                t.path = "../scripts/start-splunk.sh"
                t.env = { :SPLUNK_BIN   => "/opt/splunk/bin/splunk" }
            end

            search.vm.provision "add peer", type: "shell" do |u|
                u.privileged = false
                u.name = "Adding peer node"
                u.path = "../scripts/add_peer.sh"
                u.env = {
                    :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                    :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                    :SPLUNK_PASS  => "#{SPLUNK_PASS}"
                }
            end

            search.vm.provision "configure shcluster", type: "shell" do |u|
                u.privileged = false
                u.name = "Configure Search Head Cluster"
                u.path = "../scripts/config_shcluster.sh"
                u.env = {
                    :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                    :SPLUNK_PASS  => "#{SPLUNK_PASS}",
                    :MGMT_URI     => "#{VM_NAME}-search-#{i}:8089"
                }
            end

            if i == 3
                search.vm.provision "bootstrap captain", type: "shell" do |u|
                    u.privileged = false
                    u.name = "Bootstraping SHC Captain"
                    u.path = "../scripts/bootstrap_captain.sh"
                    u.env = {
                        :SPLUNK_HOME  => "#{SPLUNK_HOME}",
                        :SPLUNK_BIN   => "#{SPLUNK_HOME}/bin/splunk",
                        :SPLUNK_PASS  => "#{SPLUNK_PASS}"
                    }
                end
            end
        end
    end
end
